# Модуль работы с пользователями

Модуль включает функции для работы с пользователями.

## user_registration

Функция регистрирует нового пользователя и добавляет его в базу данных.

**Parametrs:**

* `name`(string): имя пользователя
* `email`(EmailString): почта пользователя, должна быть уникальной в базе данных
* `password`(string): пароль пользователя

**Returns:**

json: содержит `success: true` в случае успешной регистрации

**Raises**

UniqueException: попытка создать дубликат уникального значения

## user_login

Функция авторизует пользователя и открывает ему доступ к функциям, требующих авторизации.

**Parametrs:**

* `email`(EmailString): почта пользователя, должна быть уникальной в базе данных
* `password`(string): пароль пользователя

**Return**

json: содержит `success: true` в случае успешной авторизации

**Raises**

IndexException: пользователя с указанной почтой не существует в базе данных
ValueException: указан неверный пароль

## user_logout

Функция обеспечивает выход пользователя из приложения. Закрывает доступ к функциям, требующих авторизации.

**Parametrs**

**Return**

json: содержит `success: true` в случае успешной деавторизации

## give_priviledges

Функция открывает пользователю доступ к расширенному функционалу (взаимодействие с ошейниками).

**Parametrs:**

* `user_id`(integer): id пользователя
* `secretkey`(string): секретная последовательность символов, позволяющая открыть волонтеру доступ к работе с ошейниками

**Returns:**

json: содержит `success: true` в случае успешной работы

**Raises:**

IndexException: пользователя с указанным id не существует
ValueException: секретный ключ указан неверно

## remove_priviledges

Функция закрывает пользователю доступ к работе с ошейниками.

**Parametrs:**

* `user_id`(integer): id пользователя
* `secretkey`(string): секретная последовательность символов, позволяющая закрыть волонтеру доступ к работе с ошейниками

**Returns:**

json: содержит `success: true` в случае успешной работы

**Raises:**

IndexException: пользователя с указанным id не существует
ValueException: секретный ключ указан неверно


